### ISSUE TITLE
Tweets that are RT don't contain any Text

### ISSUE THREAD

**Issue by joelipski** [ayx-builders/proj_ayx-build-202007-tweepy#11]
![image](https://user-images.githubusercontent.com/69578207/89997708-66fef480-dc84-11ea-933a-94ee80a7657f.png)

https://twitter.com/NickMartes/status/1293436637507194881

I would also suggest adding the ability to remove RTs from the search.

**Comment by tlarsendataguy** [comment]
This is by design - it's on our to-do to have the original tweet text in a separate field, along with other fields from the original tweet.

I like the idea of removing RTs from the search.

**Comment by joelipski** [comment]
If the original tweet is included, then that would be great. It just took me a moment to guess that all the NULLs were proabbly actually RTs.

**Comment by tlarsendataguy** [comment]
We do (or should...) have a field identifying what type of tweet each record is.  It might make sense to physically move that field to the beginning, right after Id.  It gets lost at the end.
